1653301524044	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1653301808624	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1653301809078	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1653301809078	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1653301809081	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1653301809585	Sync.SyncScheduler	DEBUG	Woke from sleep.
1653301809586	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1653301809586	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1653301809587	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1653301811586	Sync.Service	DEBUG	User-Agent: Firefox/100.0.2 (Intel Mac OS X 10.15) FxSync/1.102.0.20220519220738.desktop
1653301811586	Sync.Service	INFO	Starting sync at 2022-05-23 12:30:11 in browser session y2MR3A0FOlpp
1653301811586	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1653301811589	Sync.Status	INFO	Resetting Status.
1653301811589	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1653301811589	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1653301811589	FirefoxAccounts	DEBUG	getOAuthToken enter
1653301811590	FirefoxAccounts	TRACE	getCachedToken returning cached token
1653301811590	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1653301811590	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1653301811600	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1653301811600	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1653301811601	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1653301811602	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1653301811602	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1653301811602	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1653301811602	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1653301811604	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
