1654077651166	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654077760642	Sync.RemoteTabs	INFO	Generating tab list with filter
1654077760643	Sync.RemoteTabs	DEBUG	Processing client: {"id":"Kxl_APBQpQRv","type":"client","name":"Firefox on Jirayuâ€™s iPad","clientType":"tablet","lastModified":1654006440980,"tabs":[]}
1654077760643	Sync.RemoteTabs	INFO	Final tab list has 1 clients with 1 tabs.
1654078147987	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1654078147987	Sync.Service	DEBUG	User-Agent: Firefox/100.0.2 (Linux x86_64) FxSync/1.102.0.20220520110313.desktop
1654078147987	Sync.Service	INFO	Starting sync at 2022-06-01 12:09:07 in browser session 4O5GK8xa0S1_
1654078147987	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654078148000	Sync.Status	INFO	Resetting Status.
1654078148000	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654078148001	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654078148001	FirefoxAccounts	DEBUG	getOAuthToken enter
1654078148002	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654078148002	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654078148002	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654078148004	Sync.SyncAuthManager	INFO	Getting sync key
1654078148005	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1654078148005	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1654078148005	FirefoxAccounts	DEBUG	getOAuthToken enter
1654078148005	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654078148005	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654078148005	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1654078148005	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1654078148018	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654078148019	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1654078148019	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1654078148019	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1654078148019	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1654078148024	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654078148026	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654078148026	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654078148026	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654078148027	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654078148028	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1654078148028	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654078148028	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1654078148030	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1654078148037	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
