1654031534132	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654031865911	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654031865912	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654031865921	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654031865935	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654031927740	Sync.SyncScheduler	DEBUG	Woke from sleep.
1654031927747	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1654031927747	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1654031927751	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654031929748	Sync.Service	DEBUG	User-Agent: Firefox/100.0.2 (Linux x86_64) FxSync/1.102.0.20220520110313.desktop
1654031929749	Sync.Service	INFO	Starting sync at 2022-05-31 23:18:49 in browser session 9D1uOxN2Yqm_
1654031929749	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654031929757	Sync.Status	INFO	Resetting Status.
1654031929758	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654031929759	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654031929759	FirefoxAccounts	DEBUG	getOAuthToken enter
1654031929760	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654031929760	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654031929761	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654031929763	Sync.SyncAuthManager	INFO	Getting sync key
1654031929764	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1654031929764	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1654031929764	FirefoxAccounts	DEBUG	getOAuthToken enter
1654031929765	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654031929765	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654031929765	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1654031929766	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1654031929774	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654031929775	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654031929778	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654031929779	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1654031929783	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1654031929783	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1654031929786	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1654031929792	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1654031929805	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654031929805	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654031929805	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1654031929806	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654031929807	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1654031929809	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1654031929827	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
