1654705127384	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654705128218	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654706320232	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654706320233	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654706320237	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654706320242	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654706345000	Sync.SyncScheduler	DEBUG	Woke from sleep.
1654706345000	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1654706345000	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1654706345001	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654706347001	Sync.Service	DEBUG	User-Agent: Firefox/101.0 (Linux x86_64) FxSync/1.103.0.20220602144549.desktop
1654706347001	Sync.Service	INFO	Starting sync at 2022-06-08 18:39:07 in browser session KaBVU2vXAb_K
1654706347001	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654706347004	Sync.Status	INFO	Resetting Status.
1654706347004	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654706347004	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654706347004	FirefoxAccounts	DEBUG	getOAuthToken enter
1654706347004	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654706347004	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654706347005	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654706347009	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654706347009	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654706347009	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654706347009	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654706347010	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1654706347010	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654706347010	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1654706347012	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
