1654682315043	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654682480199	Sync.RemoteTabs	INFO	Generating tab list with filter
1654682480199	Sync.RemoteTabs	DEBUG	Processing client: {"id":"Kxl_APBQpQRv","type":"client","name":"Firefox on Jirayuâ€™s iPad","clientType":"tablet","lastModified":1654642071220,"tabs":[]}
1654682480200	Sync.RemoteTabs	INFO	Final tab list has 1 clients with 1 tabs.
1654682758152	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1654682758153	Sync.Service	DEBUG	User-Agent: Firefox/101.0 (Linux x86_64) FxSync/1.103.0.20220602144549.desktop
1654682758154	Sync.Service	INFO	Starting sync at 2022-06-08 12:05:58 in browser session KaBVU2vXAb_K
1654682758155	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654682758178	Sync.Status	INFO	Resetting Status.
1654682758178	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654682758181	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654682758181	FirefoxAccounts	DEBUG	getOAuthToken enter
1654682758183	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654682758183	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654682758183	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654682759233	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654682759233	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654682759239	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654682759247	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654700291532	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1654700291575	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654700291575	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1654700291575	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1654700291576	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1654700291599	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
