1654030202411	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654030619166	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654030619166	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654030619178	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1654030619184	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654030661935	Sync.SyncScheduler	DEBUG	Woke from sleep.
1654030662056	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1654030662056	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1654030662062	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654030664060	Sync.Service	DEBUG	User-Agent: Firefox/100.0.2 (Linux x86_64) FxSync/1.102.0.20220520110313.desktop
1654030664061	Sync.Service	INFO	Starting sync at 2022-05-31 22:57:44 in browser session 9D1uOxN2Yqm_
1654030664061	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654030664067	Sync.Status	INFO	Resetting Status.
1654030664067	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654030664069	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654030664069	FirefoxAccounts	DEBUG	getOAuthToken enter
1654030664071	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654030664071	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654030664071	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654030664085	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654030664086	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654030664087	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654030664088	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654030664088	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1654030664088	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654030664089	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1654030664098	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
