1654253922653	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654253945465	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1654253945466	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654253945470	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1654253945473	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654254286401	Sync.SyncScheduler	DEBUG	Woke from sleep.
1654254286416	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1654254286416	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1654254286418	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1654254288417	Sync.Service	DEBUG	User-Agent: Firefox/100.0.2 (Linux x86_64) FxSync/1.102.0.20220520110313.desktop
1654254288418	Sync.Service	INFO	Starting sync at 2022-06-03 13:04:48 in browser session IxdYruaUuU3N
1654254288418	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1654254288425	Sync.Status	INFO	Resetting Status.
1654254288425	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1654254288427	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1654254288427	FirefoxAccounts	DEBUG	getOAuthToken enter
1654254288428	FirefoxAccounts	TRACE	getCachedToken returning cached token
1654254288428	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1654254288429	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1654254288440	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1654254288441	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1654254288442	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195039599/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654254288443	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1654254288443	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1654254288443	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1654254288444	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1654254288450	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
